"""Oracle ADF Component IDs.

This module defines Oracle ADF component identifiers used in SIA's UI.
These IDs are generated by Oracle ADF and correspond to UI components.
"""

STUDY_LEVEL_DD_ID: str = "pt1:r1:0:soc1"

CAMPUS_DD_ID: str = "pt1:r1:0:soc9"

FACULTY_DD_ID: str = "pt1:r1:0:soc2"

CAREER_DD_ID: str = "pt1:r1:0:soc3"

TIPOLOGY_DD_ID: str = "pt1:r1:0:soc4"

SHOW_COURSES_BTTN_ID: str = "pt1:r1:0:cb1"

FACULTY_CAREER_DD_ID: str = "pt1:r1:0:soc5"

CAMPUS_ELECTIVES_DD_ID: str = "pt1:r1:0:soc6"

SELECT_ROW_ID: str = "pt1:r1:0:t4"

BACK_BTTN_ID: str = "pt1:r1:1:cb4"

ORACLE_ADF_REGION_ID: str = "pt1:r1"

ORACLE_ADF_RENDER_TARGET: str = "pt1:r1"

# Oracle ADF emits this field in request payloads and it shares the same component
# id as FACULTY_CAREER_DD_ID.
ORACLE_ADF_UNKNOWN_COMPONENT_1: str = "pt1:r1:0:soc5"

ORACLE_ADF_UNKNOWN_COMPONENT_2: str = "pt1:r1:0:soc10"

ORACLE_ADF_UNKNOWN_COMPONENT_3: str = "pt1:r1:0:it10"

ORACLE_ADF_UNKNOWN_COMPONENT_4: str = "pt1:r1:0:it11"
