"""Oracle ADF Data Map.

This module defines the mapping between action identifiers and Oracle ADF component IDs/event payloads.
Used by SiaSession to construct Oracle ADF AJAX requests dynamically.
"""

from .actions import (
    BACK_BTTN,
    CAMPUS_DD,
    CAMPUS_ELECTIVES_DD,
    CAREER_DD,
    COURSE_PAGE_LINK,
    FACULTY_CAREER_DD,
    FACULTY_DD,
    SELECT_ROW,
    SHOW_COURSES_BTTN,
    STUDY_LEVEL_DD,
    TIPOLOGY_DD,
)
from .adf_events import BTTN_EVENT_VALUE, DROPDOWN_EVENT_VALUE, SELECT_ROW_EVENT_VALUE
from .adf_ids import (
    BACK_BTTN_ID,
    CAMPUS_DD_ID,
    CAMPUS_ELECTIVES_DD_ID,
    CAREER_DD_ID,
    FACULTY_CAREER_DD_ID,
    FACULTY_DD_ID,
    SELECT_ROW_ID,
    SHOW_CURSES_BTTN_ID,
    STUDY_LEVEL_DD_ID,
    TIPOLOGY_DD_ID,
)

DROPDOWNS: list[str] = [
    f"{STUDY_LEVEL_DD_ID}::content",
    f"{CAMPUS_DD_ID}::content",
    f"{FACULTY_DD_ID}::content",
    f"{CAREER_DD_ID}::content",
]

DATA_MAP: dict[str, tuple[str, str]] = {
    STUDY_LEVEL_DD: (STUDY_LEVEL_DD_ID, DROPDOWN_EVENT_VALUE),
    CAMPUS_DD: (CAMPUS_DD_ID, DROPDOWN_EVENT_VALUE),
    FACULTY_DD: (FACULTY_DD_ID, DROPDOWN_EVENT_VALUE),
    CAREER_DD: (CAREER_DD_ID, DROPDOWN_EVENT_VALUE),
    TIPOLOGY_DD: (TIPOLOGY_DD_ID, DROPDOWN_EVENT_VALUE),
    SHOW_COURSES_BTTN: (SHOW_CURSES_BTTN_ID, BTTN_EVENT_VALUE),
    FACULTY_CAREER_DD: (FACULTY_CAREER_DD_ID, DROPDOWN_EVENT_VALUE),
    CAMPUS_ELECTIVES_DD: (CAMPUS_ELECTIVES_DD_ID, DROPDOWN_EVENT_VALUE),
    SELECT_ROW: (SELECT_ROW_ID, SELECT_ROW_EVENT_VALUE),
    COURSE_PAGE_LINK: (SELECT_ROW_ID, BTTN_EVENT_VALUE),
    BACK_BTTN: (BACK_BTTN_ID, BTTN_EVENT_VALUE),
}
