"""Type stubs for sia_scraper_rust PyO3 extension module."""

from typing import Any

class SiaScraperException(Exception):
    """Custom exception raised by Rust parsing functions."""

    ...

def parse_course_info(xml: str) -> dict[str, Any]: ...
def parse_course_info_json(xml: str) -> str: ...
def extract_view_state(html: str) -> str: ...
def parse_prereqs(xml: str) -> dict[str, Any]: ...
def parse_prereqs_json(xml: str) -> str: ...
def get_course_list(html: str | bytes) -> list[dict[str, str]]: ...
def get_plain_text(xml: str) -> str: ...
def init_oracle_adf_request_dict(
    tipology_index: str,
    window_id: str | None = None,
    page_id: str | None = None,
    view_state: str | None = None,
) -> dict[str, Any]: ...
def build_oracle_adf_request_body(
    request_dict: dict[str, Any],
    data_name: str,
    idx: int,
    career_indices: list[str],
    course_list_len: int,
) -> dict[str, Any]: ...
def get_oracle_adf_event_dict(
    id: str,
    event_type: str,
    idx: int,
) -> dict[str, Any]: ...
def async_get(url: str) -> Any: ...
def async_post(url: str, body: str) -> Any: ...
def async_get_with_config(
    url: str,
    timeout: int | None = None,
    user_agent: str | None = None,
) -> Any: ...
def init_sia_session(timeout: int | None = None) -> Any: ...
def init_sia_session_json(timeout: int | None = None) -> Any: ...
def set_career(
    timeout: int | None = None,
    search_code: str = "",
    electives: bool | None = None,
) -> Any: ...
def set_career_json(
    timeout: int | None = None,
    search_code: str = "",
    electives: bool | None = None,
) -> Any: ...
def get_course_xml(
    timeout: int | None = None,
    course_index: int = 0,
    career_indices: list[str] | None = None,
    electives: bool | None = None,
) -> Any: ...
