"""SIA System Constants and Configuration.

This module defines all constants, identifiers, and configuration values for interacting
with Universidad Nacional de Colombia's SIA (Sistema de Información Académica) system,
which is built on Oracle Application Development Framework (ADF).

The SIA system uses Oracle ADF's component model, which generates dynamic IDs for UI elements
and requires specific XML payloads for AJAX interactions. Constants defined here map to:
- Oracle ADF component IDs (e.g., 'pt1:r1:0:soc1' for dropdowns)
- Oracle RichClient XML message formats for event handling
- HTTP headers required by the Oracle ADF servlet infrastructure

Note: DD = Dropdown, BTTN = Button"""

from enum import Enum

# ============================================================================
# Timeouts
# ============================================================================

# Default timeout (in seconds) for any HTTP request to SIA's Oracle ADF backend
# Used to prevent indefinite hangs when the SIA server is slow or unresponsive
DEFAULT_TIMEOUT: int = 15

# ============================================================================
# Action Identifiers - Used as keys in DATA_MAP for SIA interactions
# ============================================================================

# These constants represent logical actions in the SIA UI workflow
# They map to Oracle ADF component IDs and event types (see DATA_MAP below)

# Main course catalog search form elements
STUDY_LEVEL_DD: str = (
    "STUDY_LEVEL_DD"  # Dropdown: "Nivel de estudio" (Study level - pregrado/posgrado)
)
CAMPUS_DD: str = "CAMPUS_DD"  # Dropdown: "Sede" (Campus - Bogotá, Medellín, etc.)
FACULTY_DD: str = "FACULTY_DD"  # Dropdown: "Facultad" (Faculty/School)
CAREER_DD: str = "CAREER_DD"  # Dropdown: "Carrera" (Academic program)
TIPOLOGY_DD: str = "TIPOLOGY_DD"  # Dropdown: "Tipología" (Course typology filter)
SHOW_COURSES_BTTN: str = "SHOW_COURSES_BTTN"  # Button: "Mostrar" (Show courses)

# Elective courses search form elements
FACULTY_CAREER_DD: str = (
    "FACULTY_CAREER_DD"  # Dropdown: "Por facultad y plan" (Electives by faculty/plan)
)
CAMPUS_ELECTIVES_DD: str = (
    "CAMPUS_ELECTIVES_DD"  # Dropdown: "Por facultad" (Electives campus selector)
)

# Course list interaction elements
SELECT_ROW: str = "SELECT_ROW"  # Action: Select a table row (highlights row in UI)
COURSE_PAGE_LINK: str = "COURSE_PAGE_LINK"  # Action: Navigate to course detail page
BACK_BTTN: str = "BACK_BTTN"  # Button: "Volver" (Return to course list)

# ============================================================================
# SIA System URLs and Oracle ADF Configuration
# ============================================================================

# Base URL for SIA's public course catalog service (Oracle ADF JSF page)
SIA_BASE_URL: str = "https://sia.unal.edu.co/Catalogo/facespublico/public/servicioPublico.jsf"

# Oracle ADF Ads Page ID - Required header for ADF's AJAX partial page rendering (PPR)
# This identifies the page context for Oracle's client-side state management
ADF_ADS_PAGE_ID: str = "1"

# HTTP headers required for SIA Oracle ADF AJAX requests
# Oracle ADF validates these headers for security and proper request routing
# Note: user-agent is intentionally pinned to a specific browser version to avoid
# fingerprinting detection. SIA may reject requests with unusual browser signatures.
SIA_HEADERS: dict[str, str] = {
    "authority": "sia.unal.edu.co",
    "accept": "*/*",
    "accept-language": "es-419,es;q=0.9,en;q=0.8",
    "adf-ads-page-id": ADF_ADS_PAGE_ID,  # Oracle ADF page identifier
    "adf-rich-message": "true",  # Indicates RichClient message format expected
    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
    "origin": "https://sia.unal.edu.co",
    "referer": SIA_BASE_URL,
    "sec-ch-ua": '"Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
}
# ============================================================================
# Oracle ADF Component IDs
# ============================================================================

# These IDs are generated by Oracle ADF and correspond to UI components in the SIA interface
# Format: pt1:r1:0:soc{N} = SelectOneChoice (dropdown), pt1:r1:0:cb{N} = CommandButton
# TODO: Refactor - These are brittle dependencies on Oracle ADF's component ID generation

# Main course catalog form component IDs
STUDY_LEVEL_DD_ID: str = "pt1:r1:0:soc1"  # Dropdown for study level selection
CAMPUS_DD_ID: str = "pt1:r1:0:soc9"  # Dropdown for campus selection
FACULTY_DD_ID: str = "pt1:r1:0:soc2"  # Dropdown for faculty selection
CAREER_DD_ID: str = "pt1:r1:0:soc3"  # Dropdown for career/program selection
TIPOLOGY_DD_ID: str = "pt1:r1:0:soc4"  # Dropdown for course typology filter
SHOW_CURSES_BTTN_ID: str = "pt1:r1:0:cb1"  # "Mostrar" button to submit search

# Elective courses form component IDs
FACULTY_CAREER_DD_ID: str = "pt1:r1:0:soc5"  # Dropdown for faculty/plan in electives mode
CAMPUS_ELECTIVES_DD_ID: str = "pt1:r1:0:soc6"  # Dropdown for campus in electives mode

# Course list table and navigation component IDs
SELECT_ROW_ID: str = "pt1:r1:0:t4"  # Table component ID for row selection
BACK_BTTN_ID: str = "pt1:r1:1:cb4"  # "Volver" button to return to course list

# ============================================================================
# Oracle RichClient Event XML Payloads
# ============================================================================

# Oracle ADF uses XML messages to encode client-side events for AJAX partial page rendering
# These payloads are sent in the request body to trigger specific component behaviors

# Dropdown value change event - Triggers when user selects an option
# autoSubmit=1: Form submits immediately; suppressMessageShow=true: Hides validation messages
DROPDOWN_EVENT_VALUE: str = '<m xmlns="http://oracle.com/richClient/comm"><k v="autoSubmit"><b>1</b></k><k v="suppressMessageShow"><s>true</s></k><k v="type"><s>valueChange</s></k></m>'

# Button click event - Triggers action event on command buttons
BTTN_EVENT_VALUE: str = (
    '<m xmlns="http://oracle.com/richClient/comm"><k v="type"><s>action</s></k></m>'
)

# Table row selection event - Triggers when a table row is selected (not clicked)
SELECT_ROW_EVENT_VALUE: str = (
    '<m xmlns="http://oracle.com/richClient/comm"><k v="type"><s>selection</s></k></m>'
)

# ============================================================================
# Derived Identifiers
# ============================================================================

# Oracle ADF appends '::content' to SelectOneChoice IDs to identify the content region
# These are used for parsing dropdown options from the HTML response
DROPDOWNS: list[str] = [
    f"{STUDY_LEVEL_DD_ID}::content",
    f"{CAMPUS_DD_ID}::content",
    f"{FACULTY_DD_ID}::content",
    f"{CAREER_DD_ID}::content",
]

# ============================================================================
# Action-to-Component Mapping
# ============================================================================

# Maps logical actions to (component_id, event_xml) tuples for request body generation.
# Used by SiaSession to construct Oracle ADF AJAX requests dynamically.
# Warning: These are brittle dependencies on Oracle ADF's component ID generation.
DATA_MAP: dict[str, tuple[str, str]] = {
    # Main course search form interactions
    # Main course search form interactions
    STUDY_LEVEL_DD: (STUDY_LEVEL_DD_ID, DROPDOWN_EVENT_VALUE),  # Select study level dropdown
    CAMPUS_DD: (CAMPUS_DD_ID, DROPDOWN_EVENT_VALUE),  # Select campus dropdown
    FACULTY_DD: (FACULTY_DD_ID, DROPDOWN_EVENT_VALUE),  # Select faculty dropdown
    CAREER_DD: (CAREER_DD_ID, DROPDOWN_EVENT_VALUE),  # Select career dropdown
    TIPOLOGY_DD: (TIPOLOGY_DD_ID, DROPDOWN_EVENT_VALUE),  # Select typology dropdown
    SHOW_COURSES_BTTN: (SHOW_CURSES_BTTN_ID, BTTN_EVENT_VALUE),  # Click "Mostrar" button
    # Elective courses form interactions
    FACULTY_CAREER_DD: (FACULTY_CAREER_DD_ID, DROPDOWN_EVENT_VALUE),  # Select faculty/plan dropdown
    CAMPUS_ELECTIVES_DD: (
        CAMPUS_ELECTIVES_DD_ID,
        DROPDOWN_EVENT_VALUE,
    ),  # Select electives campus dropdown
    # Course list table interactions
    SELECT_ROW: (SELECT_ROW_ID, SELECT_ROW_EVENT_VALUE),  # Select table row (highlight)
    COURSE_PAGE_LINK: (SELECT_ROW_ID, BTTN_EVENT_VALUE),  # Click row to navigate to course page
    BACK_BTTN: (BACK_BTTN_ID, BTTN_EVENT_VALUE),  # Click "Volver" to return to list
}

# ============================================================================
# SIA-Specific Business Logic Constants
# ============================================================================

# When navigating to electives, SIA uses different internal campus codes
# Regular campus codes are 0-N, electives add this offset (e.g., Bogotá = 0 → 40 for electives)
# TODO: Refactor - Magic number should be extracted from SIA system or documented in API
ELECTIVES_CAMPUS_INCREMENT: int = 40


# ============================================================================
# Session State Enumeration
# ============================================================================


class SiaSessionStatus(Enum):
    """Represents the current state of a SIA scraping session.

    The SIA system requires sequential navigation through different pages.
    State transitions are enforced by SiaSession to maintain valid navigation.

    ## Valid Transitions
        NO_SESSION → CAREER_NOT_SET: After calling create_session()
        CAREER_NOT_SET → ON_CAREER_PAGE: After calling set_career()
        ON_CAREER_PAGE → ON_COURSE_PAGE: After selecting a course
        ON_COURSE_PAGE → ON_CAREER_PAGE: After navigating back
        Any state → NO_SESSION: After calling close_session()
    """

    NO_SESSION = "NO_SESSION"  # No active session with SIA Oracle ADF backend
    CAREER_NOT_SET = "CAREER_NOT_SET"  # Session initialized but career not selected
    ON_CAREER_PAGE = "ON_CAREER_PAGE"  # Navigated to career, viewing course list
    ON_COURSE_PAGE = "ON_COURSE_PAGE"  # Navigated to specific course details
